[package]
name = "molly-deepfilter"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "AGPL-3.0-only"
publish = false

[lib]
name = "molly_deepfilter"
crate-type = ["cdylib", "rlib"]

[dependencies]
deep_filter = { git = "https://github.com/Rikorose/DeepFilterNet", rev = "d375b2d8309e0935d165700c91da9de862a99c31", default-features = false, features = ["tract"] }
ndarray = "=0.15.6"
sha2 = "=0.10.9"
tract-core = "=0.21.4"
tract-onnx = "=0.21.4"
tract-pulse = "=0.21.4"
tract-hir = "=0.21.4"

[dev-dependencies]
hound = "=3.5.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "unwind"
strip = "debuginfo"

[workspace]
